### ISSUE TITLE
IE 11 and Edge issue

### ISSUE THREAD

**Issue by shiningkiru** [Agranom/ngx-material-timepicker#222] opened 2019-09-23 06:36 UTC
Time picker not working on IE11 and Edge. When we click on input box popup opens but when we select time then it shows invaid date message on input.

**Comment by AdditionAddict** [comment] 2019-09-23 07:47
Per SO question https://stackoverflow.com/questions/58057134/ngx-material-timepicker-not-working-on-ie-and-edge

 > I downgraded the timepicker version to 4.0.2 now it work fine both in IE and Edge.

**Comment by Agranom** [comment] 2019-09-23 10:06
I'll check it and try to fix

**Comment by aalmajanob** [comment] 2019-11-14 11:39
Dear Agranom,

  First of all, thanks very much for this great component, we are using it in our PRoyect and it works great.

  Any ETA for this bug fix?


  Regards,

**Comment by Agranom** [comment] 2019-11-14 12:56
Will try to check it on these weekends

**Comment by Sampath-Lokuge** [comment] 2019-11-26 09:54
Hi @Agranom 
Any feedback on this issue? Thanks for the great component!

**Comment by Jithesh-Menon** [comment] 2019-12-04 13:32
Hi @Agranom 
Can we expect fix for this issue in the upcoming release?

**Comment by Jithesh-Menon** [comment] 2019-12-04 13:35
> Per SO question https://stackoverflow.com/questions/58057134/ngx-material-timepicker-not-working-on-ie-and-edge
> 
> > I downgraded the timepicker version to 4.0.2 now it work fine both in IE and Edge.

Hi @AdditionAddict,
I tried this one. But when we populating the time picker through code, if we are setting the default time as "5:00", the minute section renders as "MM".

**Comment by Jithesh-Menon** [comment] 2019-12-16 06:59
Hi @Agranom,
Any comments on this issue?

Thank you.

**Comment by Agranom** [comment] 2019-12-16 08:23
Hi guys. I'm trying to find PC with windows to debug it. Because I don't have edge and IE

**Comment by Sampath-Lokuge** [comment] 2019-12-16 09:35
@Agranom I hope this will help you. It has free tier too. https://azure.microsoft.com/en-us/services/virtual-desktop/

**Comment by Agranom** [comment] 2019-12-18 12:28
@Sampath-Lokuge thanks, I'll try

**Comment by Agranom** [comment] 2019-12-27 11:31
Guys,
After debugging I've figured out that there is an issue with `luxon` library and IE supporting.
Timepicker works in Edge.
Here is the link that might help you to resolve your issue. https://moment.github.io/luxon/docs/manual/matrix.html

Please let me know whether you manage to handle or not.

**Comment by Agranom** [comment] 2020-02-29 19:39
The issue is resolved. Update to the latest version (v.5.4.0).

**Closed by Agranom** 2020-02-29 19:39 UTC
