### ISSUE TITLE
Switching between AM and PM

### ISSUE THREAD

**Issue by morgangit** [Agranom/ngx-material-timepicker#44] opened 2018-09-25 12:43 UTC
This is almost perfect! But a serious issue I've found is that if you choose a time within range, you can then switch from AM to PM (or vice versa) to take the time out of range.

The simplest way to deal with this might be to disable AM or PM switching when doing so would take whatever time is currently displaying out of range.

**Comment by Agranom** [comment] 2018-09-25 12:46
Could you reproduce this issue on https://stackblitz.com/ please?

**Comment by morgangit** [comment] 2018-09-25 12:59
Actually if you go to your demo https://agranom.github.io/ngx-material-timepicker/ and click on the "Time range from 12:10 am to 08:11 pm" example, you'll see that if you select 9.00am and then switch to pm, it'll output 9pm although it's out of range.

**Comment by Agranom** [comment] 2018-09-25 14:18
Okey, I see and I'll fix it

**Comment by morgangit** [comment] 2018-09-25 14:59
Great - thanks for you quick responses. The only other thing that's a little odd (on the same time range demo) is that when the user clicks on a time that is out of range and greyed out, rather than simply being unselectable, it selects the soones possible time, or if a time has been entered, the previous valid time. It would be far more useful if the invalid times were simply not selectable (i.e, nothing happens when you click/touch them or a snack bar message says something like "You can't select this time".)

**Comment by Agranom** [comment] 2018-10-04 15:22
Hi. Yes, I've already fix it, but lack of time to finish unit tests. But nevertheless, I'll publish fixes this weekend, sorry for this

**Comment by morgangit** [comment] 2018-10-04 15:35
Oh great. Thank you! Look forward to trying it when you publish the fixes.

**Comment by Agranom** [comment] 2018-10-07 10:36
It's ready. Update to the latest version and try

**Comment by morgangit** [comment] 2018-10-07 13:07
Hmm - I tested it. Not a great solution to the problem from a user perspective. I mean it allows you to select an invalid time, then outputs no time and logs to the console.  I assumed the goal of this clock was to prevent the user from entering invalid times according the minimum or maximum (or both) criteria set. Allowing the user to select an invalid time , press OK and then outputting no time and a console error could be achieved without changing the interface at all.  The optimal and obvious solution would be to disable actions that would make whatever time is currently displaying invalid. So disabling AM or PM switching and as I mentioned in my second comment, disabling selection of greyed out times. As I mentioned in my second comment, allowing the user to select greyed out times and then jumping to some other time that IS valid is not a viable solution in my opinion. Is it difficult to make greyed out times simply unselectable? Or disable AM PM switching?

**Comment by Agranom** [comment] 2018-10-07 21:03
Do you mean to avoid switching between am pm if the whole diale is disabled?

**Comment by morgangit** [comment] 2018-10-08 09:17
No - I mean disabling switching when switching would take whatever time is currently displayed out of range (or below the minimum or above the maximum in the other cases).  I assume this could be done by attaching a condition to the AM and PM actions. So let's say there is a time displaying in AM (AM is selected), if the user tries to switch to PM, the condition would be: IF [(PM equivalent of current display time)<(min time) or (PM equivalent of current display time)> max time)] , disable PM action. You could have snack bar error "Invalid time" or "Out of permitted range" or whatever when the user tries to switch in this case to avoid frustration.

And vice versa for switching to AM from PM.  This way, you can open the clock on the minimum time and simply make it impossible for the user to create an invalid time in the display, avoiding the scenario where the user enters and invalid time, gets a console error and then has to re-open the clock or start again - which is the same reason why I think it's better if greyed out times are simply unselectable.

**Comment by morgangit** [comment] 2018-10-08 09:37
I know what you mean, but with my suggested approach the user can switch if the currently displayed time would be valid after the switch - regards the user not understanding, a snack bar error message could solve that. It could even be more explicit "This time would not be valid in PM" or something. 

But I take your point - I think the alternative then is for switching to jump to a valid time in the other meridiem. Currently it's still possible to switch meridiems and end up with an invalid time displaying and then press OK.  So yes, I think that a reasonable alternative to my suggestion is to have the display time change to the minimum valid time of whatever meridiem the user switches to. Then, once again I think making selection of greyed out times impossible would make this a really useful clock.

**Comment by Agranom** [comment] 2018-10-08 10:07
> Currently it's still possible to switch meridiems and end up with an invalid time displaying and then press OK

It's already impossible. If user switch a period and time is not available, it selects the closest available one.

**Comment by morgangit** [comment] 2018-10-08 10:10
Oh - sorry - that's great if so. I was testing on your demo - perhaps that isn't updated yet. What do you think about making greyed out times unclickable?

**Comment by Agranom** [comment] 2018-10-08 10:56
> I was testing on your demo - perhaps that isn't updated yet

By the way, update to 2.6.3, there're some of bug fixes

**Comment by morgangit** [comment] 2018-10-08 16:15
Hi - I'm not sure if you didn't push changes or something but the latest version doesn't work as you describe above. If I switch meridiem the time remains the same even if the new time is invalid. There is no jumping to a valid time. Then you can hit 'Ok' and no time is output - just a console error - just like before.

**Comment by Agranom** [comment] 2018-10-08 16:57
Follow the link https://i.imgur.com/7a1POxD.gifv please. I  hosted there gif where it works right

**Comment by morgangit** [comment] 2018-10-08 19:41
Apologies - I was testing the time range scenario - not the minimum time only one.

**Comment by Agranom** [comment] 2018-10-10 09:45
Hi, okay. I hope I'll fix it today

**Comment by Agranom** [comment] 2018-10-12 07:18
I published 2.6.4, where I fixed bug with clicking on disabled hours. 
Unfortunately I run out of time to fix disable switching between periods this week. I hope I'll do it the next week

**Comment by morgangit** [comment] 2018-10-12 08:53
Ok thanks. I don't think you need to disable switching between periods. I think the approach you half-implemented where you don't disable switching but the time jumps to the earliest possible time on switching is a fine approach if you complete it. The problem is just that when minutes are selected, this doesn't work right now. Completing your approach I guess would mean that even if minutes are selected, the hour would have to jump to the earliest possible valid hour given the restrictions entered.

**Comment by morgangit** [comment] 2018-10-22 17:49
Hi Agranom - any plan to release with a fix for the AM-PM switching issue that remains when minutes are selected?

**Comment by Agranom** [comment] 2018-10-22 18:01
Hi. Could you please tell me steps to reproduce it, because I'm a little bit confused )

**Comment by morgangit** [comment] 2018-10-22 18:09
Ok - an easy way to reproduce it using your demo. Go to the time range example (12.10am to 8.11pm) and switch to AM and pick 9, then 20 in minues to get 9.20am. Now switch to PM and you get 9.20pm (out of range!) and you can press OK to get no output - error logged to console.

Or quicker:
1. Click AM
2. Click 9
3. Click pm
You get 9pm and can click OK.

This clock would be most useful if you simply can't get a time out range to display. So in this case when you have 9.20AM displaying, when you go to switch to PM it should jump to 8.11pm as that's the nearest possible valid time. Either that or it could jump to 7.20PM, just moving the hour to make it valid. Either solution would work well.

**Comment by Agranom** [comment] 2018-10-23 10:11
Hmm, I see. However, I guess that it's easier just to avoid user switching between periods and show some kind of warn or error message.

**Comment by morgangit** [comment] 2018-10-23 14:15
Yes that would be another approach - and easier to implement I imagine. But I think it would be strange to have half-implemented an approach of jumping to a valid time when hours are selected and half-implemented an approach where switching is disabled if minutes happen to be selected. It would be inconsistent UX. When switching would cause an invalid time to display, either you can't switch - with a snack bar error showing ("Switching periods would take this time out of range" or something) , or switching should jump to a valid time in the period you switched to. Either would work fine - but not both. One strategy when hour is selected and another when minutes are selected would be quite bad.

**Comment by Agranom** [comment] 2018-10-25 07:35
I've implemented avoiding switching between periods thing for now, because I have some important issues to resolve. Once I accomplish them, I'll try to implement it in your way.

**Comment by morgangit** [comment] 2018-10-25 08:47
Hey Agranom - ok, thanks - by the way your snack bar error should be 'There **IS** no available time for this period' but I think that's a little unclear (which period? Also it implies that the entire period is out of range). I'd suggest changing the error to something like 'Current time would be invalid in this period'. Another issue is that the error never disappears! It should disappear after 3 seconds or so.

**Comment by Agranom** [comment] 2018-10-25 09:33
Ops, thanks for mention it, I'll change.

**Comment by morgangit** [comment] 2018-10-29 10:36
Hey - please let me know when the snack bar error problem I mentioned is fixed!

**Comment by Agranom** [comment] 2018-10-29 20:27
already published.

**Comment by morgangit** [comment] 2018-10-29 21:03
Great. Thank you! Do you want me to close this issue or do you still plan to implement the consistent solution of changing to a valid time on switching (the way it works when hour is selected)?

**Comment by Agranom** [comment] 2018-10-30 09:57
I close it for now and once I finish other issues I'll try to implement your idea

**Closed by Agranom** 2018-10-30 09:57 UTC
