### ISSUE TITLE
ngx-timepicker-field problem with HH input in 12 hours format

### ISSUE THREAD

**Issue by Anrehecil** [Agranom/ngx-material-timepicker#243] opened 2019-10-18 14:02 UTC
Focus input - backspace to clear hours = no placeholder, but digit 1 appears...
I can't type hours between 2 and 9 in hours field without using arrows or select all in input (only in 12 hours format) http://prntscr.com/pl40zu

**Comment by Agranom** [comment] 2019-10-22 10:19
will check

**Comment by robert-king** [comment] 2019-10-23 23:16
not sure if this is the same issue or not, but i'm getting "0" instead of "00" - not sure if that's by design or not, not a big issue though. 

<img width="217" alt="Screen Shot 2019-10-24 at 12 12 54 PM" src="https://user-images.githubusercontent.com/793016/67441095-043a5f00-f658-11e9-9c30-c32cc45d8b34.png">
<img width="206" alt="Screen Shot 2019-10-24 at 12 12 59 PM" src="https://user-images.githubusercontent.com/793016/67441096-04d2f580-f658-11e9-83e0-2fa2e5f744d6.png">
<img width="280" alt="Screen Shot 2019-10-24 at 12 13 33 PM" src="https://user-images.githubusercontent.com/793016/67441097-04d2f580-f658-11e9-9457-3b832158a1fe.png">
<img width="667" alt="Screen Shot 2019-10-24 at 12 14 47 PM" src="https://user-images.githubusercontent.com/793016/67441098-04d2f580-f658-11e9-8995-7ce9d980c16d.png">


Thanks for a great library. One more thing - Luxon.js does add some bloat just fyi.

**Comment by Anrehecil** [comment] 2019-10-27 23:18
@Agranom any chance you will fix problem with hours input in 12h format field?

**Comment by Agranom** [comment] 2019-10-28 11:58
Yes, I will. Just need more time for that

**Comment by Agranom** [comment] 2019-11-02 18:04
It should be fixed. Update to v5.2.2 and check please

**Comment by Dona278** [comment] 2019-11-04 11:40
@Agranom I've the same issue with 24h format and v5.2.2.
If I have a number already set from model or if I have the input placeholder then the first input is taken and formatted (eg. "2" => "02").
I reproduced the issue also in this way:

Initial state: 11:00
![image](https://user-images.githubusercontent.com/10567243/68117818-b0086800-fefe-11e9-89ff-443f7b58a8be.png)

Go on hours input with tab or mouse, then press "2"
![image](https://user-images.githubusercontent.com/10567243/68117730-69b30900-fefe-11e9-8df5-82eff6b3fa0d.png)
No other input allowed

Go to the minutes input and return back to the hours (or lose and gain focus), press "2" again;
![image](https://user-images.githubusercontent.com/10567243/68118030-3fae1680-feff-11e9-879a-fec9b12d55fb.png)
Digits aren't formatted and now the input field accept another input before formatting, even if I move to another element and then go back.

Same issue with input placeholer as initial state.

**Comment by Agranom** [comment] 2019-11-04 12:30
Are you facing this bug on the demo page? Because I cannot reproduce it.

**Comment by Dona278** [comment] 2019-11-04 13:43
Yes!

Initial state:
![image](https://user-images.githubusercontent.com/10567243/68125207-5198b500-ff11-11e9-82d9-3e5f5cfd88dd.png)

After press "1"
![image](https://user-images.githubusercontent.com/10567243/68125270-7e4ccc80-ff11-11e9-84ec-405735a49d57.png)

**Comment by Agranom** [comment] 2019-11-04 14:00
I see the different bug ) When I press '1' an hour changes to '02' instead of '01'. But not bug with formatting

**Comment by Agranom** [comment] 2019-11-21 15:38
Update to v5.2.3 and check pls

**Comment by Dona278** [comment] 2019-11-21 21:19
Same issue..

**Comment by Agranom** [comment] 2019-12-21 09:34
@Dona278 could you pls describe the bug ?

**Comment by AdditionAddict** [comment] 2020-01-23 10:17
Different platform keyboard behaviour of the ngx-timepicker-field:-

**iPad**
- works well typing '11' results in '11'
- doesn't matter where cursor is if clicking into field
- tabbing into field also works
- keyboard shows letters rather than numbers (possible fix is to put type="tel" on the input)

**Desktop (Chrome / Firefox)**
- practically unusable
- typing '11' results in '01' no matter where cursor is or if you tab into hour/minute field
- only way to enter is type '1', back arrow, delete (←), type '1' or to use up/down arrows which is slow

**Comment by Agranom** [comment] 2020-01-23 15:59
Did you try on window desktop?

**Comment by AdditionAddict** [comment] 2020-01-23 16:43
> 
> 
> Did you try on window desktop?

Apologies above was for Windows (post edited to reflect)

**Comment by Agranom** [comment] 2020-02-18 08:30
Do you use right side numbers on your keyboard?

**Comment by Agranom** [comment] 2020-02-29 19:42
The issue is resolved. Update to the latest version (v.5.4.0).

**Closed by Agranom** 2020-02-29 19:42 UTC
