### ISSUE TITLE
Switching format from 12h to 24h leads to error on picker

### ISSUE THREAD

**Issue by yl-endress** [Agranom/ngx-material-timepicker#198] opened 2019-09-09 09:38 UTC
Hey guys,

whenever I changed the current format type from 12h to 24h, the picker leads to an error when going > 12 or < 1.

![image](https://user-images.githubusercontent.com/44203645/64520361-4f8ded80-d2f6-11e9-89c6-d09aa3ba1421.png)

**Details**
The form starts in the 12h format (hoursFormat=12).
Depending on format settings it's dynamically changed.

`                <ngx-timepicker-field
                    [defaultTime]="currentTimeControl.value"
                    [formControl]="currentTimeControl"
                    [format]="hoursFormat"
                    [toggleIcon]="timePickerIcon">
                 </ngx-timepicker-field>
                  <ng-template #timePickerIcon>
                    <span class="my-icon"></span>
                  </ng-template>`

Debugging with Augury let me observe, that the amount of available hours is not updated. Initially the array hoursList is an array of 12 elements. 
![image](https://user-images.githubusercontent.com/44203645/64520142-cc6c9780-d2f5-11e9-8604-6d59c984f323.png)

After changing the format, the array is not updated.
![image](https://user-images.githubusercontent.com/44203645/64520205-ee661a00-d2f5-11e9-8f1e-012c13d3e0ab.png)

I expected the hourList is updated properly on it's own whenever the format is changed (like max. hours does).

**Comment by Agranom** [comment] 2019-09-09 09:46
Hi. I know about that bug. I've just thought that it's not so neccessary, but I see, that it becames more useful feature. So I'll add possibility to change format dynamically.

**Comment by Agranom** [comment] 2019-09-09 11:21
how do you change format? Because I cannot reproduce that bug. Hours list changes as expected

**Comment by yl-endress** [comment] 2019-09-09 11:28
<ngx-timepicker-field [defaultTime]="currentTimeControl.value" [formControl]="currentTimeControl" **[format]="hoursFormat"** [toggleIcon]="timePickerIcon">


**ts part**
export class MyComponent {
  hoursFormat = 24;

private setHoursFormat(timeFormat: string) {
    this.hoursFormat = timeFormat.includes("a") ? 12 : 24;
  }
}

Sorry I forgot to mention that I am forced to use version 3.3.1 cause of compiler issue:
```
WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 230:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 289:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
```

**Comment by yl-endress** [comment] 2019-09-09 12:48
Somehow it looks like the function [getHours()](https://github.com/Agranom/ngx-material-timepicker/blob/master/src/app/material-timepicker/utils/timepicker-time.utils.ts)  is not executed properly @my place.

`    @Input()
    set format(value: number) {
        this._format = value === 24 ? 24 : 12;
        this.minHour = this._format === 12 ? 1 : 0;
        this.maxHour = this._format === 12 ? 12 : 23;
        this.hoursList = getHours(this._format);
    }
`

I copy pasted it to my ts and call it manually.... now it seems to work... I have no idea why it's behaving as it does, because the namespace should not be a problem (getHours shouldn't be overwritten)....

**ts part**
export class MyComponent {
  @ViewChild("timePickerField") timePickerField;

  private setHoursFormat(timeFormat: string) {
    this.hoursFormat = timeFormat.includes("a") ? 12 : 24;
    if (this.timePickerField) {
      this.timePickerField.format = this.hoursFormat;
      this.timePickerField.hoursList = this.getHours(this.hoursFormat);
      console.log(this.timePickerField);
      console.log(this.getHours(12));
      console.log(this.getHours(24));
      debugger;
    }
  }

  private getHours(format: number): ClockFaceTime[] {
    return Array(format).fill(1).map((v, i) => {
      const angleStep = 30;
      const time = v + i;
      const angle = angleStep * time;
      return {time: time === 24 ? 0 : time, angle};
    });
  }

Can you please put the utils functions into your [public api](https://github.com/Agranom/ngx-material-timepicker/blob/master/public_api.ts) ? So I can reuse them :-)

**Comment by Agranom** [comment] 2019-09-09 12:55
Already figured out the issue. Will be fixed soon

**Comment by Agranom** [comment] 2019-09-11 13:51
You can try it now. But you have to use the latest version which is now v5.1.0

**Comment by yl-endress** [comment] 2019-09-13 07:35
Thank you!

Unfortunately I am not able to test it because we still use Angular 7, that leads to compiler errors (ng s will lead to empty white screen)

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 238:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 297:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 323:33-51
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 323:117-125
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 323:153-161
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 323:179-187
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 323:199-207
"export 'ɵɵinject' was not found in '@angular/core'
i ｢wdm｣: Compiled with warnings.

=> I have to wait until we updated to 8.x . So far I simply trust in your development ;)

**Closed** 2019-09-13 07:35 UTC
