### ISSUE TITLE
Invalid DateTime 

### ISSUE THREAD

**Issue by moon-web75** [Agranom/ngx-material-timepicker#423] opened 2023-02-09 13:19 UTC
I have updated chrome browser and then I am facing invalid DateTime and also your demo project facing same issue

Please refer this screenshot
![image (4)](https://user-images.githubusercontent.com/95608631/217824343-2cfef7fa-2247-471d-8495-e97a818b60c2.png)

**Comment by Giandrys** [comment] 2023-02-09 17:46
I have the same problem...

**Comment by pablomgs3** [comment] 2023-02-09 19:15
I've spent the whole day trying to fix this myself but the problem is only happening on chrome. The issue seems to be related with chrome's locale format and how luxon parses the locale.

As a workaround, you can switch to the 24hr format in your input **[format]="24"**

Hope this helps until @Agranom can find a fix for this.

**Comment by CodeWorldIndustries** [comment] 2023-02-10 05:23
There hasn't been a release in over 3 years. Is no one maintaining this package anymore?

**Comment by CodeWorldIndustries** [comment] 2023-02-10 05:34
If anyone is looking for an alternative, check out igx-time-picker. I think its better. Especially for mobile devices.

**Comment by moon-web75** [comment] 2023-02-10 05:56
> There hasn't been a release in over 3 years. Is no one maintaining this package anymore?
@CodeWorldIndustries I think no one is managing its package in the last 3 years 😔.

**Comment by wratte** [comment] 2023-02-12 17:14
I found the problem causing this issue and I have been able to it. The default numbering sustem "latn" used to parse the time in locale string returns a Narrow No-Break Space (NNBSP) instead of standard space which cause the parse to fail. It doesn't happen for the 24h format because it uses another parsing system which is based on ISO time. If you need a quick fix you can add the following line of code at line 34 in the time-adapter.ts ".replace(/\u202F/g, ' ');" I don't know if this package is still maintained anymore but I could try to fork it and create a new version with the patch. Let me know if you're interested.

**Comment by ashishpCACTUS** [comment] 2023-02-13 08:44
@wratte  - Checking if you would be able to generate a patch. We are trying but not able to successfully run the solution as it is a older version of Angular and other dependencies

**Comment by wratte** [comment] 2023-02-13 23:01
@ashishpCACTUS @CodeWorldIndustries - I forked, pull requested and the changes has been accepted by a contributor. Unfortunatly the unit tests are not working anymore probably due to the fact that this was not maitained for a long period of time. It will take make time to rewrite those tests. I'll see what I can do but I'm not to familiar with the luxon library dependency tests.

**Comment by anandhv02** [comment] 2023-02-14 09:24
@pablomgs3. You said, change the format from 12hr to 24hr. But it will show the time pop out like 24 format UI. But I am expecting the UI should be visible like 12hr format. How do I change that ?

**Comment by clarnjan** [comment] 2023-02-14 11:05
> @pablomgs3. You said, change the format from 12hr to 24hr. But it will show the time pop out like 24 format UI. But I am expecting the UI should be visible like 12hr format. How do I change that ?
I managed to use 12hr format by downgrading the package to version 4.0.2

**Comment by pablomgs3** [comment] 2023-02-14 15:27
Update chrome to the lastest version (Version 110.0.5481.97 (Official Build))
It is working now :)

**Closed** 2023-06-08 10:38 UTC
